
package exam_palindromo;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.Normalizer;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import javax.swing.JOptionPane;


public class Palindromo extends javax.swing.JFrame {

    private String frase;
    private Queue<Character> cola;
    private Stack<Character> pila;
    
    public Palindromo() {
        initComponents();
        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension D = tool.getScreenSize();
        setSize(465,280);
        setLocation((D.width-getSize().width)/2,(D.height-getSize().height)/2);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        txtFrase.setEditable(false);
        cola = new LinkedList();
        pila = new Stack();
        setTitle("VERIFICADOR DE PALINDROMOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lbFrase = new javax.swing.JLabel();
        txtFrase = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        lbRespuesta = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(171, 217, 249));
        getContentPane().setLayout(null);

        title.setBackground(new java.awt.Color(0, 33, 255));
        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(204, 204, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("IDENTIFICADOR DE PALINDROMOS");
        title.setOpaque(true);
        getContentPane().add(title);
        title.setBounds(20, 20, 410, 40);

        lbFrase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbFrase.setText("FRASE:");
        getContentPane().add(lbFrase);
        lbFrase.setBounds(20, 80, 60, 20);

        txtFrase.setText("Introduzca Su Frase");
        txtFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraseActionPerformed(evt);
            }
        });
        getContentPane().add(txtFrase);
        txtFrase.setBounds(80, 80, 350, 22);

        btnVerificar.setBackground(new java.awt.Color(55, 123, 243));
        btnVerificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(204, 204, 255));
        btnVerificar.setText("LIMPIAR");
        btnVerificar.setOpaque(true);
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar);
        btnVerificar.setBounds(160, 130, 120, 23);

        lbRespuesta.setBackground(new java.awt.Color(255, 252, 105));
        lbRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbRespuesta.setForeground(new java.awt.Color(71, 67, 0));
        lbRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRespuesta.setText("RESPUESTA");
        lbRespuesta.setOpaque(true);
        getContentPane().add(lbRespuesta);
        lbRespuesta.setBounds(90, 180, 260, 30);

        btnSalir.setBackground(new java.awt.Color(0, 0, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(370, 210, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFraseActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        if (btnVerificar.getText()=="LIMPIAR"){
            
            btnVerificar.setText("VERIFICAR");
            txtFrase.setEditable(true);
            txtFrase.setText("");
            lbRespuesta.setBackground(new Color(255,252,105));
            lbRespuesta.setForeground(new Color(71,67,0));
            lbRespuesta.setText("RESPUESTA");
            
            pila.clear();
            cola.clear();
            
        } else {
            frase = txtFrase.getText().toLowerCase();
            frase = Normalizer.normalize(frase, Normalizer.Form.NFD).replaceAll("\\p{M}", "");
            char c;
            for (int i = 0; i < frase.length(); i++){
                c = frase.charAt(i);
                if (!Character.isSpaceChar(c)){
                    cola.add(c);
                    pila.push(c);
                }
            }
            
            if (!cola.isEmpty()){
                boolean esTru = true;
               
                for (int i = 0; i < pila.size(); i++) {
                    if (!pila.pop().equals(cola.poll())){
                        esTru = false;
                        break;
                    }
                }  
                
                if (esTru) {
                    lbRespuesta.setBackground(new Color(61,255,74));
                    lbRespuesta.setForeground(new Color(0,57,5));
                    lbRespuesta.setText("ES PALINDROMO");
                } else {
                    lbRespuesta.setBackground(new Color(252,46,46));
                    lbRespuesta.setForeground(new Color(79,0,0));
                    lbRespuesta.setText("NO ES PALINDROMO");
                }
                btnVerificar.setText("LIMPIAR");
                txtFrase.setEditable(false);
            } else {
                txtFrase.setText("");
                JOptionPane.showMessageDialog(getMe(), "[ERROR]: NO SE INGRESO NINGUNA FRASE", "IDENTIFICADOR DE PALINDROMOS", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (JOptionPane.showConfirmDialog(getMe(), "Seguro que desea Salir?", "IDENTIFICADOR DE PALINDROMOS", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private Palindromo getMe(){
        return this;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel lbFrase;
    private javax.swing.JLabel lbRespuesta;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtFrase;
    // End of variables declaration//GEN-END:variables
}
